# deploy a fully functional development environment as a statefulset
# check https://github.com/onichandame/docker-dev for docs
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: http-gateway
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin
spec:
  gateways:
    - http-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: dev
            port:
              number: 3000
  hosts:
    - "*"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-user
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: api-access
rules:
  - apiGroups:
      - ""
      - apps
      - autoscaling
      - batch
      - extensions
      - policy
      - rbac.authorization.k8s.io
    resources:
      - componentstatuses
      - configmaps
      - daemonsets
      - deployments
      - events
      - endpoints
      - horizontalpodautoscalers
      - ingress
      - jobs
      - limitranges
      - namespaces
      - nodes
      - pods
      - pods/log
      - persistentvolumes
      - persistentvolumeclaims
      - resourcequotas
      - replicasets
      - replicationcontrollers
      - serviceaccounts
      - services
    verbs: ["*"]
  - nonResourceURLs: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: api-access
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: api-access
subjects:
  - kind: ServiceAccount
    name: admin-user
    namespace: default
---
apiVersion: v1
kind: Service
metadata:
  name: dev
spec:
  ports:
    - name: dev
      port: 3000
      targetPort: 3000
  selector:
    app: dev
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev
spec:
  selector:
    matchLabels:
      app: dev
  replicas: 1
  template:
    metadata:
      labels:
        app: dev
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: dev
          image: "registry.cn-hangzhou.aliyuncs.com/onichandame/docker-dev:latest"
          imagePullPolicy: Always
          tty: true
          ports:
            - containerPort: 3000
              name: dev-port
          volumeMounts:
            - mountPath: /<workspace> # mount your workspace to pod
              name: git-storage
          env:
            - name: GIT_USER_NAME
              value: "onichandame"
            - name: GIT_USER_EMAIL
              value: "zxinmyth@gmail.com"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - kind-worker # match the name of the node where files are mounted
      volumes:
        - name: git-storage
          hostPath:
            path: /<workspace> # your workspace in a worker node
            type: Directory
