# deploy a soft IOC for development purpose.
apiVersion: v1
kind: Service
metadata:
  name: epics
spec:
  ports:
  - name: epics
    port: 5064
    targetPort: 5064
  selector:
    app: epics
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: epics
  labels:
    app: epics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: epics
  template:
    metadata:
      labels:
        app: epics
    spec:
      containers:
      - name: epics
        image: onichandame/epics:example
        tty: true
        ports:
          - containerPort: 5064
            name: default-port
        readinessProbe:
          tcpSocket:
            port: default-port
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: default-port
          initialDelaySeconds: 15
          periodSeconds: 20
