# deploy a nats server for development purpose
apiVersion: v1
kind: Service
metadata:
  name: ipfs
spec:
  ports:
  - name: ipfs
    port: 4001
    targetPort: 4001
  - name: api
    port: 5001
    targetPort: 5001
  - name: gateway
    port: 8080
    targetPort: 8080
  selector:
    app: ipfs
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ipfs
  labels:
    app: ipfs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ipfs
  template:
    metadata:
      labels:
        app: ipfs
    spec:
      containers:
      - name: ipfs
        image: ipfs/go-ipfs:latest
        ports:
          - containerPort: 4001
            name: ipfs
          - containerPort: 5001
            name: api
          - containerPort: 8080
            name: gateway
        readinessProbe:
          tcpSocket:
            port: ipfs
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: ipfs
          initialDelaySeconds: 15
          periodSeconds: 20
