apiVersion: v1
kind: PersistentVolume
metadata:
  name: git-storage
spec:
  capacity:
    storage: 500Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: git-storage
  local:
    path: /hosthome/xiao/git # match the directory containing all your workspaces
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - minikube # match the name of the node where files reside
