name: Publish Docker
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Begin Publish
        uses: actions/checkout@master
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: onichandame/docker-dev
          username: ${{ secrets.DOCKER_USERNAME }}
          password : ${{ secrets.DOCKER_PASSWORD }}
