name: Publish Docker
on: [push]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare repo
        uses: actions/checkout@master
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: onichandame/docker-dev
          username: ${{ secrets.DOCKER_USERNAME }}
          password : ${{ secrets.DOCKER_PASSWORD }}
  aliyun:
    runs-on: ubuntu-latest
    needs: [publish]
    steps:
      - name: Sync image to Aliyun
        uses: onichandame/docker-registry-sync-action:master
        with:
          source_repository: 'docker.io/onichandame/docker-dev'
          target_repository: 'registry.cn-shanghai.aliyuncs.com/onichandame/docker-dev'
          target_username: ${{ secrets.ALIYUN_IMAGES_HUB_USER_NAME }}
          target_password: ${{ secrets.ALIYUN_IMAGES_HUB_TOKEN }}
