name: Publish Docker
on:
  push:
    branches:
      - "main"
      - "master"
    paths-ignore:
      - "kube/**"
      - ".github/**"
jobs:
  build-base:
    name: Build Base Image
    runs-on: ubuntu-latest
    steps:
      - name: Prepare repo
        uses: actions/checkout@master
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: onichandame/docker-dev
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
  aliyun-sync-base:
    name: Sync Base to Aliyun
    runs-on: ubuntu-latest
    needs: [build-base]
    steps:
      - name: Sync image to Aliyun
        uses: onichandame/docker-registry-sync-action@master
        with:
          source_repository: "docker.io/onichandame/docker-dev"
          target_repository: "registry.cn-hangzhou.aliyuncs.com/onichandame/docker-dev"
          target_username: ${{ secrets.ALIYUN_IMAGES_HUB_USER_NAME }}
          target_password: ${{ secrets.ALIYUN_IMAGES_HUB_TOKEN }}
  build-china:
    name: Build China Image
    runs-on: ubuntu-latest
    needs: [publish]
    steps:
      - name: Prepare repo
        uses: actions/checkout@master
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: onichandame/docker-dev
          tags: 'china'
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: Dockerfile.china
  aliyun-sync-china:
    name: Sync China to Aliyun
    runs-on: ubuntu-latest
    needs: [build-china]
    steps:
      - name: Sync image to Aliyun
        uses: onichandame/docker-registry-sync-action@master
        with:
          source_repository: "docker.io/onichandame/docker-dev:china"
          target_repository: "registry.cn-hangzhou.aliyuncs.com/onichandame/docker-dev:china"
          target_username: ${{ secrets.ALIYUN_IMAGES_HUB_USER_NAME }}
          target_password: ${{ secrets.ALIYUN_IMAGES_HUB_TOKEN }}
